POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Blogi random käyttäjällä (ensimmäinen) varustettuna",
    "author": "Paappa",
    "url": "http://www.koodarivekkulit.com/hu3rr3r3r3bbaaa",
    "likes": 600
}