POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "4.2 blogilista step2 vaiheen blogi",
    "author": "HardcoderX",
    "url": "http://www.koodarivekkulit.com/blaablaa",
    "likes": 500

}